name: transport
description: A starting point for Dart libraries or applications.
version: 1.0.7
homepage: https://github.com/CimZzz/transport

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  encrypt: ^4.0.0
  pointycastle: ^1.0.2
  console_cmd: ^1.0.5
  stream_data_reader: ^1.0.6

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
