name: transport
description: A starting point for Dart libraries or applications.
version: 1.0.1
homepage: https://github.com/CimZzz/transport

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  console_cmd: ^1.0.5

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
